version: '3'
services:
  mongodb:
    image: mongo:5.0.12
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
  app:
    build:
      context: .
      target: development
    command: npm run test
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./ipfs:/user/src/app
    ports:
      - 4000:4000
