version: '3'
services:
  app:
    build:
      context: .
      target: development
    command: npm run test:cov
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
