version: '3'
services:
  mongodb:
    image: mongo:5.0.12
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=ipfs

    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      target: development
    command: npm run start:dev
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    restart: always
