version: '3'
services:
  ipfs_host:
    image: ipfs/kubo:latest
    container_name: ipfs_host
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
    volumes:
      - ./ipfs/staging/:/export
      - ./ipfs/data/:/data/ipfs

  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    volumes:
      - /db/data:/data/db
    ports:
      - '27017:27017'
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - .env

  app:
    build:
      context: .
      target: development
    command: npm run start:dev
    depends_on:
      - mongo
      - ipfs_host
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    restart: always
